### ISSUE TITLE
bash build.sh problem 

### ISSUE THREAD

**Issue by Ninjaa90** [yubrajbhoi/termux-python-12#1] opened 2024-02-25 22:24 UTC
![Screenshot_20240226-002246_Termux](https://github.com/yubrajbhoi/termux-python-12/assets/61499147/88c165fd-d64c-44c8-a13d-712566ae731d)
When I use this command:- bash build.sh , this happens

**Comment by yubrajbhoi** [comment] 2024-03-09 04:26
Try `chmod +x ./configure` and run `bash build.sh` again.

**Comment by Ninjaa90** [comment] 2024-03-09 12:41
> @Ninjaa90 Try `chmod +x ./configure` and run `bash build.sh` again.

not working same problem

**Comment by yubrajbhoi** [comment] 2024-03-09 12:47
@Ninjaa90 That is strange. Try this. Add `bash` in front of the `configure` command in `build.sh` file.

Like this:

```bash
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_file__dev_ptmx=yes ac_cv_file__dev_ptc=no ac_cv_func_wcsftime=no"
# Avoid trying to include <sys/timeb.h> which does not exist on android-21:
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_ftime=no"
# Avoid trying to use AT_EACCESS which is not defined:
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_faccessat=no"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" --with-system-ffi --with-system-expat --without-ensurepip"
# Hard links does not work on Android 6:
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_linkat=no"
# Do not assume getaddrinfo is buggy when cross compiling:
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_buggy_getaddrinfo=no"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" --enable-loadable-sqlite-extensions"
# Fix https://github.com/termux/termux-packages/issues/2236:
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_little_endian_double=yes"
# Force enable posix semaphores.
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_posix_semaphores_enabled=yes"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_open=yes"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_timedwait=yes"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_getvalue=yes"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_unlink=yes"
# Force enable posix shared memory.
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_shm_open=yes"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_shm_unlink=yes"

export CC=clang
export CXX=clang++
export LDFLAGS='-landroid-posix-semaphore -landroid-support -Wl,--as-needed'
export LIBCRYPT_LIBS='-lcrypt'
export CPPFLAGS='-D__ANDROID_API__=24 -Wno-implicit-function-declaration'
export CFLAGS='-Wno-implicit-function-declaration -Wno-int-conversion'
mkdir target

bash ./configure --prefix="$PWD/target" $TERMUX_PKG_EXTRA_CONFIGURE_ARGS 2>&1 | tee conf.log
make -j6 2>&1 | tee build.log
make install

rm ./target/bin/2to3
rm ./target/bin/idle3
rm ./target/bin/pydoc3
rm ./target/bin/python3
rm ./target/bin/python3-config

rm ./target/lib/pkgconfig/python3-embed.pc
rm ./target/lib/pkgconfig/python3.pc
```

**Comment by Ninjaa90** [comment] 2024-03-09 12:58
> @Ninjaa90 That is strange. Try this. Add `bash` in front of the `configure` command in `build.sh` file.
> 
> Like this:
> 
> ```shell
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS="ac_cv_file__dev_ptmx=yes ac_cv_file__dev_ptc=no ac_cv_func_wcsftime=no"
> # Avoid trying to include <sys/timeb.h> which does not exist on android-21:
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_ftime=no"
> # Avoid trying to use AT_EACCESS which is not defined:
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_faccessat=no"
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" --with-system-ffi --with-system-expat --without-ensurepip"
> # Hard links does not work on Android 6:
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_linkat=no"
> # Do not assume getaddrinfo is buggy when cross compiling:
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_buggy_getaddrinfo=no"
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" --enable-loadable-sqlite-extensions"
> # Fix https://github.com/termux/termux-packages/issues/2236:
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_little_endian_double=yes"
> # Force enable posix semaphores.
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_posix_semaphores_enabled=yes"
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_open=yes"
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_timedwait=yes"
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_getvalue=yes"
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_sem_unlink=yes"
> # Force enable posix shared memory.
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_shm_open=yes"
> TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" ac_cv_func_shm_unlink=yes"
> 
> export CC=clang
> export CXX=clang++
> export LDFLAGS='-landroid-posix-semaphore -landroid-support -Wl,--as-needed'
> export LIBCRYPT_LIBS='-lcrypt'
> export CPPFLAGS='-D__ANDROID_API__=24 -Wno-implicit-function-declaration'
> export CFLAGS='-Wno-implicit-function-declaration -Wno-int-conversion'
> mkdir target
> 
> bash ./configure --prefix="$PWD/target" $TERMUX_PKG_EXTRA_CONFIGURE_ARGS 2>&1 | tee conf.log
> make -j6 2>&1 | tee build.log
> make install
> 
> rm ./target/bin/2to3
> rm ./target/bin/idle3
> rm ./target/bin/pydoc3
> rm ./target/bin/python3
> rm ./target/bin/python3-config
> 
> rm ./target/lib/pkgconfig/python3-embed.pc
> rm ./target/lib/pkgconfig/python3.pc
> ```

![Uploading Screenshot_20240309-145658_Termux.jpg…]()

**Comment by Ninjaa90** [comment] 2024-03-09 13:01
This happens 
https://ibb.co/tpF1rny
Unable to upload here

**Comment by Ninjaa90** [comment] 2024-03-09 13:02
![photo_2024-03-09_15-02-34](https://github.com/yubrajbhoi/termux-python-12/assets/61499147/61778660-8132-4284-966b-825cfdc16523)

**Comment by yubrajbhoi** [comment] 2024-03-09 13:06
That is happening because you have the code in your `~/storage` folder. Move the git repo to your home folder like this:

```bash
cd ..
mv termux-python-12 $HOME/
cd $HOME/termux-python-12
bash build.sh
```

**Comment by Ninjaa90** [comment] 2024-03-09 13:23
it worked but python version still 3.11
![Uploading photo_2024-03-09_15-22-58.jpg…]()

**Comment by Ninjaa90** [comment] 2024-03-09 13:24
it worked but python version still 3.11
![photo_2024-03-09_15-22-58](https://github.com/yubrajbhoi/termux-python-12/assets/61499147/40e49462-7eb5-4eb8-b10f-bb9b55dc488c)

**Comment by Ninjaa90** [comment] 2024-03-09 13:29
![photo_2024-03-09_15-27-39](https://github.com/yubrajbhoi/termux-python-12/assets/61499147/917423f9-517f-4295-9e97-cffbbde0decb)

**Comment by yubrajbhoi** [comment] 2024-03-09 13:33
@Ninjaa90 Try `python3.12 -v`.

**Comment by yubrajbhoi** [comment] 2024-03-09 13:37
@Ninjaa90 Actually Python was not built correctly. Install `libandroid-spawn` and try again.

**Comment by Ninjaa90** [comment] 2024-03-09 13:37
![photo_2024-03-09_15-37-14](https://github.com/yubrajbhoi/termux-python-12/assets/61499147/ec47231e-71d4-4179-aedb-820a5334a415)

**Comment by Ninjaa90** [comment] 2024-03-09 13:38
> @Ninjaa90 Actually Python was not built correctly. Install `libandroid-spawn` and try again.

OK

**Comment by Ninjaa90** [comment] 2024-03-09 13:44
I have previously installed python using command pkg install python
should I have not done that ?

**Comment by yubrajbhoi** [comment] 2024-03-09 13:46
@Ninjaa90 No, that is good actually. This version is installed separately. And `python` will install the dep libraries.

**Comment by Ninjaa90** [comment] 2024-03-09 13:50
> @Ninjaa90 No, that is good actually. This version is installed separately. And `python` will install the dep libraries.

I'm a beginner 
I Don't know how to run python 3.12
And I Don't know how to use libandroid-spawn ( no videos on YouTube)

**Comment by yubrajbhoi** [comment] 2024-03-09 13:53
@Ninjaa90 Install with `pkg install libandroid-spawn` and run `build.sh` again.

Honestly building from source on Termux is pretty hard as a beginner. Maybe I should upload a binary package.

**Comment by yubrajbhoi** [comment] 2024-03-21 05:56
@Ninjaa90 Binary package is too big to upload here, let me know if you still want it. Closing this as completed.

**Closed by yubrajbhoi** 2024-03-21 05:56 UTC

**Comment by Ninjaa90** [comment] 2024-03-21 13:02
> @Ninjaa90 Binary package is too big to upload here, let me know if you still want it. Closing this as completed.

OK,  but I need to know how to use it too , thank you so much

**Comment by yubrajbhoi** [comment] 2024-03-21 13:22
@Ninjaa90 Here is the binary package:

https://pub-bd75ef878d714a3eba64b1c6226079b6.r2.dev/python-3.12.1-aarch64.tar.zst

To install it first make sure these packages are installed with `pkg install` or `apt install`. Here is the list: `python`, `stow`, `zstd`, `tar`, `build-essential`, `curl`.

Here is how to install them all:

```bash
apt install python stow zstd tar build-essential curl
```

Here is how to download and install the package:

```bash
curl -O -L 'https://pub-bd75ef878d714a3eba64b1c6226079b6.r2.dev/python-3.12.1-aarch64.tar.zst'
tar xf python-3.12.1-aarch64.tar.zst
mkdir -p $PREFIX/stow
mv python-3.12.1 $PREFIX/stow/
cd $PREFIX/stow
stow -v --stow python-3.12.1
```

You can copy and paste that intro termux. Confirm it is correctly installed like this:

```
python3.12 --version
```

**Comment by zrekryu** [comment] 2024-08-29 20:33
Hi, after following the last comment's codes, I received this error:

```bash
.../usr/stow $ python3.12 --version             CANNOT LINK EXECUTABLE "python3.12": cannot locate symbol "close_range" referenced by "/data/data/com.termux/files/usr/stow/python-3.12.1/bin/python3.12"...
```

**Comment by yubrajbhoi** [comment] 2024-08-30 05:01
@zrekryu Hey, I have updated the package to `Python-3.12.5`. Try it out. If that still does not work you will have to build it on your device.

**Comment by zrekryu** [comment] 2024-08-30 14:45
Hey, that didn't work, so I tried cloning the repo and using build.sh in a proot-distro (proot-distro login debian), and it worked there! Thank you so much for this repo!

**Comment by TSSlade** [comment] 2024-09-17 16:21
@yubrajbhoi - I'm getting the same issues zrekryu had at that last step:
`.../usr/stow $ python3.12 --version             CANNOT LINK EXECUTABLE "python3.12": cannot locate symbol "close_range" referenced by "/data/data/com.termux/files/usr/stow/python-3.12.5/bin/python3.12"...`

Any sense what I might be doing wrong? Or an alternative workaround?

**Comment by yubrajbhoi** [comment] 2024-09-17 16:25
@TSSlade The issue is that I am compiling the binary package on my Google Pixel 6a. If your device is different you might get bugs like this. The only solution is to build from source on your device. That should work without any bugs.

**Comment by yubrajbhoi** [comment] 2024-09-17 16:33
@TSSlade There is one in `README.md`.

**Comment by TSSlade** [comment] 2024-09-17 16:36
Oh, so just clone and then `bash build.sh`. Sorry I missed that. Thanks!

**Comment by TSSlade** [comment] 2024-09-17 17:43
Actually, oddly enough, it appears that even though the `stow` commands earlier were throwing error messages, an (unrelated) OS update to my tablet may have changed something and made them work? I downloaded the repo and was going to install it, but along the way executed `$ python3.12 --version` and things magically worked. ¯\_(ツ)_/¯

Thanks!
